// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Employeesqlc struct {
	ID         int32
	Name       string
	Age        int32
	Department string
	Salary     float64
	City       string
}
