// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const createEmployee = `-- name: CreateEmployee :exec

INSERT INTO employeesqlc(

name,
age,
department,
salary,
city

)

VALUES(?,?,?,?,?)
`

type CreateEmployeeParams struct {
	Name       string
	Age        int32
	Department string
	Salary     float64
	City       string
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) error {
	_, err := q.db.ExecContext(ctx, createEmployee,
		arg.Name,
		arg.Age,
		arg.Department,
		arg.Salary,
		arg.City,
	)
	return err
}

const deleteEmployee = `-- name: DeleteEmployee :exec

DELETE

FROM employeesqlc

WHERE id=?
`

func (q *Queries) DeleteEmployee(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteEmployee, id)
	return err
}

const getEmployee = `-- name: GetEmployee :one

SELECT id, name, age, department, salary, city

FROM employeesqlc

WHERE id=?
`

func (q *Queries) GetEmployee(ctx context.Context, id int32) (Employeesqlc, error) {
	row := q.db.QueryRowContext(ctx, getEmployee, id)
	var i Employeesqlc
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Age,
		&i.Department,
		&i.Salary,
		&i.City,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many

SELECT id, name, age, department, salary, city

FROM employeesqlc
`

func (q *Queries) ListEmployees(ctx context.Context) ([]Employeesqlc, error) {
	rows, err := q.db.QueryContext(ctx, listEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employeesqlc
	for rows.Next() {
		var i Employeesqlc
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.Department,
			&i.Salary,
			&i.City,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :exec

UPDATE employeesqlc

SET

name=?,
age=?,
department=?,
salary=?,
city=?

WHERE id=?
`

type UpdateEmployeeParams struct {
	Name       string
	Age        int32
	Department string
	Salary     float64
	City       string
	ID         int32
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) error {
	_, err := q.db.ExecContext(ctx, updateEmployee,
		arg.Name,
		arg.Age,
		arg.Department,
		arg.Salary,
		arg.City,
		arg.ID,
	)
	return err
}
